### ISSUE TITLE
File modes should be more strict

### ISSUE THREAD

**Issue by porglezomp** [powderblock/PyDankReddit#30]
Files should be opened using a mode that indicates what's going to be done with them.
A large offender that I found immediately as I started looking as lines `35-38`, which contain `"a+"` when the only thing that's being done with the file is reading from it.

In general, use the most restrictive possible format that you can. (`"r"` for something you only read from, `"a"` if you're appending but not reading, etc.)

**Comment by powderblock** [comment]
a+ in lines 35-38 is done as a way to create those files if they don't exist. This will later be required for #12.  

Is there a better way to do this? If so, how?

**Comment by porglezomp** [comment]
In general you should manually check if a file exists and if it doesn't, create it. You can check if a file exists using `os.path.isfile(filename)`, and you can create it file by doing `open(filename, 'a').close()` if it doesn't exists.

**Comment by porglezomp** [comment]
I can tackle this and #12 if you want?
