### ISSUE TITLE
\u2026 is Breaking Tweeting

### ISSUE THREAD

**Issue by powderblock** [powderblock/PyDankReddit#33]
When tweeting, including the \u2026 character results in a UnicodeEncodeError from Tweepy.  

This seems to be fixed (according to: [this stackoverflow question](http://stackoverflow.com/questions/14382662/converting-tweets-to-string-in-python)) By using unicode() instead of our current system of str().

**Comment by powderblock** [comment]
@porglezomp was right. This only crops up when non uni messages are sent.

**Comment by porglezomp** [comment]
What??
No, it's caused by any messages that are unicode instead of ASCII. `\u2026` is the unicode "…" character. Try replacing instances of `str` with `unicode` and see what breaks then.
