### ISSUE TITLE
Date format breaks when writing occurs exactly on a second

### ISSUE THREAD

**Issue by powderblock** [powderblock/PyDankReddit#46]
"%Y-%m-%d %H:%M:%S.%f" causes a crash when trying to write exactly on a second.  

Example: 2015-02-01 05:45:05

**Comment by powderblock** [comment]
Moving this into a try except block.

**Comment by powderblock** [comment]
Think I fixed this one. Testing.

**Comment by powderblock** [comment]
So. If an entry is made ON THE SECOND then when we parse karma.txt, it breaks. In the try except block we need to add a section which adds some rubbish values.  

That would be a kludge method, but it would work, be easy, and *kind* of clean. The better method is just to re write all values with no float values at the end. But since the old karma.txt has floats, it would require reworking karma.txt.

**Comment by porglezomp** [comment]
That's easy, just make a script that reads the data and spits it back out without the fractions.
