### ISSUE TITLE
Define bot Account User Name as Variable

### ISSUE THREAD

**Issue by powderblock** [powderblock/PyDankReddit#51]
Just something like:
botUser = "foobar_example123"

It should be a string.
Replace all instances of "DEAL_WITH_IT_bot" with botUser or whatever the var is named.  

This will help the flexibility issues @porglezomp mentioned in #48.

**Comment by porglezomp** [comment]
HARDCODE NOTHING WOO!

**Comment by porglezomp** [comment]
I think this is probably a good time to make a more general config.txt that you can put lots of information in.

**Comment by powderblock** [comment]
Lots of information such as user and pass? Or what?

**Comment by porglezomp** [comment]
It could include that, how are you currently doing that?

**Comment by powderblock** [comment]
I have different files for each account and service.
So currently I have lots of different txt files for each account on Imgur, Twitter, and reddit. Then I parse all those using a regex and plug in the info that is found into vars. I log into the services using the resulting vars.

Not only would having config.txt be easier and cleaner, the code would look much better. Currently I have something like five different regexs(?), one for each account. This may have just been me not knowing how to regex when I wrote the code but writing it all in one file would be :+1:

**Comment by porglezomp** [comment]
I can try to make a config manager for you!

**Comment by porglezomp** [comment]
If we can talk privately (Facebook or something) then I can be more helpful here, I need a few of the artifact/private files to test stuff out if that's okay with you.
